package com.example.ankit_pc.foodmania;

/**
 * Created by Ankit_PC on 05/24/2015.
 */
import android.content.Context;
import android.content.ContentValues;
import android.database.DatabaseErrorHandler;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
public class DBHelper extends SQLiteOpenHelper {
        private static final int DATABASE_VERSION=1;
        private static final String DATABASE_NAME="restaurants.db";
        public static final String TABLE1="listofrestaurants";
        public static final String COLUMN_ID="_id";
        public static final String COLUMN_RESTAURANTNAME="name";
        public static final String COLUMN_AREA="area";
        public static final String COLUMN_ZIPCODE="zipcode";
        public static final String COLUMN_MINIMUM_AMOUNT="min";
        public static final String COLUMN_DELIVERYTIME="dt";
        //public static final String COLUMN_IMAGEICON="img";
        public static final String TABLE2="categories";
        public static final String COLUMN_ID1="id1";
        public static final String COLUMN_CATEGORY="category";
        public static final String COLUMN_RESTAURANTID="resid";
        public static final String TABLE3="fooditems";
        public static final String COLUMN_ID2="id2";
        public static final String COLUMN_MENU="fooditem";
        public static final String COLUMN_PRICE="price";
        public static final String COLUMN_VNEG="vng";
        public static final String COLUMN_CATEGORYID="id1";
    public DBHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, DATABASE_NAME, factory, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        String query="CREATE TABLE " + TABLE1 + "(" +
                COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT," +
                COLUMN_RESTAURANTNAME + " TEXT," +
                COLUMN_AREA + " TEXT," +
                COLUMN_ZIPCODE + " INT," +
                COLUMN_MINIMUM_AMOUNT + " INT," +
                COLUMN_DELIVERYTIME + " INT" +
               // COLUMN_IMAGEICON + " TEXT" +
                ")";
        String query1="CREATE TABLE " + TABLE2 + "(" +
                COLUMN_ID1 + " INTEGER PRIMARY KEY AUTOINCREMENT," +
                COLUMN_CATEGORY + " TEXT," +
                COLUMN_RESTAURANTID + " INT," +
                " FOREIGN KEY ("+COLUMN_RESTAURANTID+") REFERENCES "+TABLE1+" ("+COLUMN_ID+")"+
                ")";
        String query2="CREATE TABLE " + TABLE3 + "(" +
                COLUMN_ID2 + " INTEGER PRIMARY KEY AUTOINCREMENT," +
                COLUMN_MENU + " TEXT," +
                COLUMN_PRICE + " DOUBLE," +
                COLUMN_VNEG + " TEXT," +
                COLUMN_CATEGORYID + " INT," +
                " FOREIGN KEY ("+COLUMN_CATEGORYID+") REFERENCES "+TABLE2+" ("+COLUMN_ID1+")"+
                ")";
        db.execSQL(query);
        db.execSQL(query1);
        db.execSQL(query2);
    }
   /* @Override
      public void onCreate(SQLiteDatabase db) {
        String CREATE_PRODUCTS_TABLE = "CREATE TABLE " +
                TABLE_PRODUCTS + "("
                + COLUMN_ID + " INTEGER PRIMARY KEY," + COLUMN_PRODUCTNAME
                + " TEXT," + COLUMN_QUANTITY + " INTEGER" + ")";
        db.execSQL(CREATE_PRODUCTS_TABLE);
    }*/
    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            db.execSQL("DROP TABLE IF EXISTS " + TABLE1);
            onCreate(db);
    }

    public long createRestaurant(String name, String area,
                              int zip, int min ,int del) {
        SQLiteDatabase db=this.getWritableDatabase();
        ContentValues initialValues = new ContentValues();
        initialValues.put(COLUMN_RESTAURANTNAME, name);
        initialValues.put(COLUMN_AREA, area);
        initialValues.put(COLUMN_ZIPCODE, zip);
        initialValues.put(COLUMN_MINIMUM_AMOUNT, min);
        initialValues.put(COLUMN_DELIVERYTIME, del);
       // initialValues.put(COLUMN_IMAGEICON, img);
        return db.insert("listofrestaurants", null, initialValues);
    }

    public long createCategories(String catName, int rest_id
                                 ) {
        SQLiteDatabase db=this.getWritableDatabase();
        ContentValues initialValues = new ContentValues();
        initialValues.put(COLUMN_CATEGORY, catName);
        initialValues.put(COLUMN_RESTAURANTID, rest_id);
        return db.insert("categories", null, initialValues);
    }
    public void insertRestaurants() {
//        createRestaurant("Lunasia Chinese Cuisine","Alhambra",91801,30,40,"R.drawable.daisymint2");
//        createRestaurant("Savoy Kitchen","Alhambra",91801,25,35,"R.drawable.savoy");
//        createRestaurant("The Boiling Crab","Alhambra",91801,20,30,"R.drawable.boilingcrab");
//        createRestaurant("Wahib's Middle East Restaurant & Bakery","Alhambra",91801,30,25,"R.drawable.wahib");
//        createRestaurant("Daisy Mint","Pasadena",91106,20,20,"R.drawable.daisymint");
//        createRestaurant("All India Cafe","Pasadena",91106,20,40,"R.drawable.allindiacafe");
//        createRestaurant("Green Street Restaurant","Pasadena",91106,25,25,"R.drawable.greenstreet");
//        createRestaurant("Animal Restaurant","Los Angeles",90036,30,35,"R.drawable.animalrest");
//        createRestaurant("Pizzeria Mozza","Los Angeles",90036,20,40,"R.drawable.pizzeria");
        createRestaurant("Lunasia Chinese Cuisine","Alhambra",91801,30,40);
        createRestaurant("Savoy Kitchen","Alhambra",91801,25,35);
        createRestaurant("The Boiling Crab","Alhambra",91801,20,30);
        createRestaurant("Wahib's Middle East Restaurant & Bakery","Alhambra",91801,30,25);
        createRestaurant("Daisy Mint","Pasadena",91106,20,20);
        createRestaurant("All India Cafe","Pasadena",91106,20,40);
        createRestaurant("Green Street Restaurant","Pasadena",91106,25,25);
        createRestaurant("Animal Restaurant","Los Angeles",90036,30,35);
        createRestaurant("Pizzeria Mozza","Los Angeles",90036,20,40);
        createCategories("Steam Dishes",1);
        createCategories("Baked & Deepfried Dishes",1);
        createCategories("Rice Noodles",1);
        createCategories("Chef Specialty",1);
        createCategories("Soup & Salad & Appetizers",2);
        createCategories("Pasta",2);
        createCategories("Curry",2);
        createCategories("House Specialty",2);
        createCategories("Pizza",2);
        createCategories("Dessert",2);
        createCategories("Git Down N Dirty",3);
        createCategories("Fried",3);
        createCategories("Extras",3);
        createCategories("Appetizers",4);
        createCategories("Salads",4);
        createCategories("Sandwiches",4);
        createCategories("Lunch / Dinner Special",4);
        createCategories("Kebabs",4);
        createCategories("Seafood",4);
        createCategories("Vegetarian Plates",4);
        createCategories("Wahib's Specials",4);
        createCategories("APPETIZER",5);
        createCategories("SOUP",5);
        createCategories("SIDE ORDER & EXTRA",5);
        createCategories("SALAD",5);
        createCategories("NOODLE SOUP",5);
        createCategories("NOODLES",5);
        createCategories("RICE",5);
        createCategories("STIR FRY VEGGIES",5);
        createCategories("MEAT & POULTRY",5);
        createCategories("HOUSE SPECIALTIES",5);
        createCategories("APPETIZERS",6);
        createCategories("SOUP AND SALADS",6);
        createCategories("VEGETARIAN ENTREES",6);
        createCategories("TANDOORI ENTREES",6);
        createCategories("NON VEGETARIAN CURRIES",6);
        createCategories("INDIAN BREADS AND RICE",6);
        createCategories("BEVERAGES",6);
        createCategories("BREAKFAST ",7);
        createCategories("GRAINS",7);
        createCategories("BAKERY",7);
        createCategories("SCRAMBLES AND BRUNCH",7);
        createCategories("BENEDICTS",7);
        createCategories("HASH",7);
        createCategories("OMELETTES",7);
        createCategories("FROM THE GRIDDLE",7);
        createCategories("EGG BREAKFASTS",7);
        createCategories("FROM THE BAR",7);
        createCategories("BEVERAGES",7);
        createCategories("Main",8);
        createCategories("APPETIZERS",9);
        createCategories("SALADS",9);
        createCategories("MEAT",9);
        createCategories("BRUSCHETTA",9);
        createCategories("PANINI",9);
        createCategories("DISHES OF THE DAY",9);
        createCategories("PIZZA",9);
        createCategories("WHITE DINAPOLI TOMATO",9);
        createCategories("CONFECTIONERY",9);
        createMenu("Jumbo Shrimp Har-gow",3.58,1,"n");
        createMenu("Jumbo Pork Sil-mai",4.58,1,"n");
        createMenu("Steamed Chicken Feet",3.58,1,"n");
        createMenu("Spareribs Black Bean Sauce",3.58,1,"n");
        createMenu("Supreme Beef Balls",2.58,1,"n");
        createMenu("Vegetarian Dumplings",3.58,1,"v");
        createMenu("Foie-gras Dumpling",4.58,1,"n");
        createMenu("Bbq Pork Buns",2.58,2,"n");
        createMenu("Snow-cap Buns",2.58,2,"n");
        createMenu("Baked Chicken Buns",3.58,2,"n");
        createMenu("Pan Fried Fried Pot Sticker",4.58,2,"n");
        createMenu("Deep Fried Taro Cake",3.58,2,"v");
        createMenu("Shrimp Rice Noodles",4.58,3,"n");
        createMenu("Beef Rice Noodles",3.58,3,"n");
        createMenu("Egg Roll Rice Noodles",4.58,3,"n");
        createMenu("Bbq Pork Rice Noodles",3.58,3,"n");
        createMenu("Veggie Rice Noodles",4.58,3,"v");
        createMenu("Braised Mushroom W/ Brown Sauce",5.98,4,"n");
        createMenu("Deep Fried Beans Curd Skin Wrap",5.98,4,"n");
        createMenu("Hot And Spicy Squids",6.98,4,"n");
        createMenu("Hot And Spicy Chicken Wing",6.98,4,"n");
        createMenu("Hot And Spicy Chicken Tender",6.98,4,"n");
        createMenu("Chicken Broth",1.5,5,"n");
        createMenu("Cold Pasta Salad",6.25,5,"v");
        createMenu("Garden Salad",2.5,5,"v");
        createMenu("Pizza Bread",1.5,5,"v");
        createMenu("Seafood Garden Salad",3.5,5,"n");
        createMenu("Tomato & Herb Pasta",5.75,6,"v");
        createMenu("Chicken Pasta",5.95,6,"n");
        createMenu("Sausage & Pepper Pasta",5.95,6,"v");
        createMenu("Savory's Traditional Pasta",5.95,6,"n");
        createMenu("Creamy Mushrooms Prosciutto Pasta",6.75,6,"n");
        createMenu("Curry Chicken",5.95,7,"n");
        createMenu("Curry Beef Stew",5.95,7,"n");
        createMenu("Curry Beef",5.95,7,"n");
        createMenu("Curry Pork Chop",5.95,7,"n");
        createMenu("Hainan Chicken Rice",5.75,8,"n");
        createMenu("Baked Halibut",6.95,8,"n");
        createMenu("Baked Seafood Casserole",6.95,8,"n");
        createMenu("Roasted Cornish Hen",5.75,8,"n");
        createMenu("Filet Mignon",9.75,8,"n");
        createMenu("Mozzarella Of Savory Pizza",6.75,9,"n");
        createMenu("Original Roast Garlic Chicken Pizza",7.75,9,"n");
        createMenu("Italian Sausage Pizza",7.75,9,"n");
        createMenu("Three Mushrooms Pizza",7.75,9,"n");
        createMenu("Seafood Combination Pizza",8.75,9,"n");
        createMenu("Creme Bruleee",1.5,10,"n");
        createMenu("Oysters",9,10,"n");
        createMenu("Shrimp",9,10,"n");
        createMenu("Clams",10,10,"n");
        createMenu("Mussels",9,10,"n");
        createMenu("Fried Catfish Basket",10,11,"n");
        createMenu("Fried Shrimp Basket",10,11,"n");
        createMenu("Chicken Tenders Basket",7,11,"n");
        createMenu("Fried Oysters",10,11,"n");
        createMenu("Fried Calamari",10,11,"n");
        createMenu("Cajun Or Lp Hot Wings",7,11,"n");
        createMenu("Gumbo",6,12,"n");
        createMenu("Corn On The Cob",0.75,12,"n");
        createMenu("Potatoes",1.5,12,"v");
        createMenu("Sausages",8,12,"v");
        createMenu("Cajun Fries",3,12,"n");
        createMenu("Sweet Potato Fries",4,12,"v");
        createMenu("Steamed Rice",2,12,"v");
        createMenu("Extra Condiments",0.5,12,"v");
        createMenu("Fava Beans Foul Moudamas",5.99,13,"n");
        createMenu("Hummos",4.99,13,"v");
        createMenu("Imtabbal Babaghanouj",4.99,13,"n");
        createMenu("Kubbeh Balls(5 Pieces)",4.99,13,"n");
        createMenu("Falafel (6 Pieces)",4.99,13,"v");
        createMenu("Labneh Plate",4.99,13,"n");
        createMenu("Feta Cheese Plate",4.99,13,"n");
        createMenu("Grape Leaves Doulma Or Cabbage Rolls With Lamb",6.99,13,"n");
        createMenu("Vegetarian Grape Leaves Doulma Or Cabbage Rolls",6.99,13,"v");
        createMenu("Lentil Soup",3.49,13,"v");
        createMenu("Rice Pilaf",3.49,13,"n");
        createMenu("Vegetarian Rice",3.5,13,"v");
        createMenu("Fattoush",6.99,14,"n");
        createMenu("Tabbouleh",5.49,14,"n");
        createMenu("Lebanese Garden Salad",3.99,14,"n");
        createMenu("Combination Salad",8.45,14,"n");
        createMenu("Cucumber With Yogurt",5.99,14,"n");
        createMenu("Armenian Salad",6.99,14,"n");
        createMenu("Greek Salad",5.99,14,"v");
        createMenu("Chicken Salad",7.25,14,"v");
        createMenu("Shawarma Beef Or Chicken",5.99,15,"n");
        createMenu("Lamb, Beef Or Chicken Sandwich",5.99,15,"n");
        createMenu("Kafta (lula)",5.99,15,"n");
        createMenu("Falafel",4.99,15,"v");
        createMenu("Fish Sandwich",5.99,15,"n");
        createMenu("Kebabs",8.95,16,"n");
        createMenu("Vegetarian Plate",8.95,16,"n");
        createMenu("Stew",8.95,16,"n");
        createMenu("1/4 Baked Chicken",8.95,16,"n");
        createMenu("Lamb",8.95,16,"n");
        createMenu("Fish Of The Day",8.95,16,"n");
        createMenu("New- Spicy Chicken",8.95,16,"n");
        createMenu("New - Numi Special",8.95,16,"n");
        createMenu("Kafta Lula Kebabs",13.95,17,"n");
        createMenu("Chicken Kababs",14.45,17,"n");
        createMenu("Lamb Or Beef Kababs",14.95,17,"n");
        createMenu("Shrimp Kababs",12.95,17,"n");
        createMenu("Lamb Liver Kebab",12.95,17,"n");
        createMenu("Filet Of Fish",13.95,18,"n");
        createMenu("Fresh Whole Fish",14.95,18,"n");
        createMenu("Spicy Shrimp Saute Or Fish",14.95,18,"n");
        createMenu("Shrimp Kebab",14.95,18,"n");
        createMenu("Falafel With Tahini",10.95,19,"n");
        createMenu("Falafel With Hummos Or Imtabbal",10.95,19,"n");
        createMenu("Falafel With Tabbouleh",10.95,19,"n");
        createMenu("Falafel Combination",11.95,19,"n");
        createMenu("Fried Califlower With Tabbouleh",10.95,19,"n");
        createMenu("Grape Leaves Doulma Vegetarian",10.95,19,"v");
        createMenu("Cabbage Rolls Vegetarian",10.95,19,"v");
        createMenu("Combination Vegetarian",11.95,19,"v");
        createMenu("Combination Vegetarian With Zucchini",10.95,19,"v");
        createMenu("Curry And Vegetable Stew",10.95,19,"v");
        createMenu("Fresh Okra Stew",10.95,19,"v");
        createMenu("Eggplant Vegetarian Supreme",10.95,19,"v");
        createMenu("Lamb Chops Saute Or Barbecue",19.95,20,"n");
        createMenu("Quail Saute Or Barbecue",15.95,20,"n");
        createMenu("Frog Legs Saute",15.95,20,"n");
        createMenu("Lamb Liver Raw Or Saute",12.95,20,"n");
        createMenu("Spicy Chicken",12.95,20,"n");
        createMenu("Spicy Beef Or Lamb",12.95,20,"n");
        createMenu("Hummos Topped With Chicken",13.95,20,"n");
        createMenu("Hummos Topped With Beef Or Lamb Saute",13.95,20,"n");
        createMenu("Shawarma Beef Or Chicken Saute",13.95,20,"n");
        createMenu("Sliced Chicken Barbecue",12.95,20,"n");
        createMenu("Sliced Beef Barbecue",13.95,20,"n");
        createMenu("Armenian Sausage Sujouk",13.95,20,"n");
        createMenu("Lebanese Sausage Maqaneq",12.95,20,"n");
        createMenu("New - Numi Special",13.95,20,"n");
        createMenu("Egg Rolls",2.95,21,"n");
        createMenu("Summer Rolls",2.95,21,"n");
        createMenu("Crab Meat Cheese Wonton",4.95,21,"n");
        createMenu("Pollack Wraps",4.95,21,"n");
        createMenu("Peanut Dumplings",4.95,21,"n");
        createMenu("Tofu Delight",4.95,21,"n");
        createMenu("Peanut Dumplings",4.95,21,"n");
        createMenu("Chicken Sate",6.95,21,"n");
        createMenu("Daisy Wing",6.95,21,"n");
        createMenu("Salmon Wraps",6.95,21,"n");
        createMenu("Beef",5.95,22,"n");
        createMenu("Shrimp",6.95,22,"n");
        createMenu("Seafood",9.95,22,"n");
        createMenu("Tofu Soup",4.95,22,"n");
        createMenu("Steamed White Or Brown Rice",1.5,23,"v");
        createMenu("Sticky Rice Or Lemongrass Rice",2.5,23,"v");
        createMenu("Steamed Vegetable",4.5,23,"v");
        createMenu("Peanut Sauce",1.5,23,"v");
        createMenu("Cucumber Relish",1.5,23,"n");
        createMenu("Curry Sauce",3.5,23,"n");
        createMenu("Extra Tofu Or Meat",2,23,"n");
        createMenu("House Salad",4.95,24,"n");
        createMenu("Steak Salad",10.95,24,"n");
        createMenu("Spicy Catfish",12.95,24,"n");
        createMenu("Garden Grilled",8.95,24,"n");
        createMenu("Eggplant Salad",8.95,24,"n");
        createMenu("Waterfall Pork",10.95,24,"n");
        createMenu("Beef Noodle Soup",7.95,25,"n");
        createMenu("Duck Noodle Soup",8.95,25,"n");
        createMenu("Pad See Ew",8.95,26,"n");
        createMenu("Spicy Spaghetti",11.95,26,"n");
        createMenu("Pad Thai",11.95,26,"n");
        createMenu("Daisy Noodles",8.95,26,"n");
        createMenu("Spaghetti & Black Mussel",11.95,26,"n");
        createMenu("Glass Noodles Shrimp",11.95,26,"n");
        createMenu("Spaghetti & Seafood",15.95,26,"n");
        createMenu("Egg Fried Rice",8.995,27,"n");
        createMenu("Spicy Fried Rice",8.95,27,"n");
        createMenu("Kimchi Fried Rice",9.95,27,"n");
        createMenu("Pineapple Delight",10.95,27,"n");
        createMenu("Daisy Fried Rice",11.95,27,"n");
        createMenu("Spicy Bamboo",8.95,28,"n");
        createMenu("Mushroom & Ginger",8.95,28,"n");
        createMenu("Garlic String Bean",8.95,28,"n");
        createMenu("Spicy Eggplant",8.95,28,"n");
        createMenu("Pumpkin",8.95,28,"n");
        createMenu("Chilies & Basil",8.95,29,"n");
        createMenu("Cashew Nuts",8.95,29,"n");
        createMenu("Peanut Chicken",9.955,29,"n");
        createMenu("Honey Pork",10.95,29,"n");
        createMenu("Korean Ribeye",16.95,29,"n");
        createMenu("Daisy Back Rib",20.95,29,"n");
        createMenu("Salmon Curry",11.95,30,"n");
        createMenu("Daisy Salmon",11.95,30,"n");
        createMenu("Sizzling Seafood",16.95,30,"n");
        createMenu("Ginger Fish",14.95,30,"n");
        createMenu("Sev Puri",5.5,31,"n");
        createMenu("Bhel Puri",5.5,31,"n");
        createMenu("Dahi Potato Puri",6.5,31,"n");
        createMenu("Shrimp Chat",8.95,31,"n");
        createMenu("Aloo Tikki",3.95,31,"n");
        createMenu("Uttapam",6.95,31,"n");
        createMenu("Mixed Chutneys",4.5,31,"n");
        createMenu("Samosas",4.55,31,"n");
        createMenu("Vegetarian Pakoras",6.95,31,"n");
        createMenu("Onion Pakoras",5.95,31,"n");
        createMenu("Chicken Pakoras",7.95,31,"n");
        createMenu("Shrimp Pakoras",8.95,31,"n");
        createMenu("Fish Pakoras",8.95,31,"n");
        createMenu("Paneer Pakora",8.95,31,"n");
        createMenu("Masala Dosa",8.95,31,"n");
        createMenu("Chicken Soup",4.5,32,"n");
        createMenu("Vegetarian Soup",4.5,32,"n");
        createMenu("Sambar",3.95,32,"n");
        createMenu("Tandoori Chicken Salad",9.95,32,"n");
        createMenu("Tandoori Fish Salad",11.95,32,"n");
        createMenu("Shrimp Salad",11.95,32,"n");
        createMenu("Vegetarian Tandoori Salad",9.95,32,"n");
        createMenu("Eggplant Salad",6.95,32,"n");
        createMenu("Tossed Green Salad",4.95,32,"n");
        createMenu("Vegetable of the Day",9.95,33,"n");
        createMenu("Mixed Vegetable",8.95,33,"n");
        createMenu("Baingan Bharta",8.95,33,"n");
        createMenu("Gobi Aloo",8.95,33,"n");
        createMenu("Aloo Mattar",8.95,33,"n");
        createMenu("Palak Aloo",8.95,33,"n");
        createMenu("Makhni Paneer",9.95,33,"n");
        createMenu("Palak Paneer",9.95,33,"n");
        createMenu("Shahi Paneer",9.95,33,"n");
        createMenu("Kabuli Cholay",8.95,33,"n");
        createMenu("Dal of the Day",7.95,33,"n");
        createMenu("Malai Kofta",8.95,33,"n");
        createMenu("Palak Tofu",8.95,33,"n");
        createMenu("Tofu Tikka Masala",8.95,33,"n");
        createMenu("Navaratan Korma",8.95,33,"n");
        createMenu("Tandoori Chicken",11.95,34,"n");
        createMenu("Chicken Tikka",12.95,34,"n");
        createMenu("Lamb Sheesh Kabab",13.95,34,"n");
        createMenu("Lamb Boti Kabab",14.95,34,"n");
        createMenu("Fish Tikka",15.95,34,"n");
        createMenu("Tandoori Shrimp",15.95,34,"n");
        createMenu("Tandoori Platter",15.95,34,"n");
        createMenu("Green Chicken Tikka",12.95,34,"n");
        createMenu("Chicken Curry",11.95,35,"n");
        createMenu("Nirvana Chicken",12.95,35,"n");
        createMenu("Chicken Makhni",12.95,35,"n");
        createMenu("Lamb Makhni",14.95,35,"n");
        createMenu("Lamb Curry",13.95,35,"n");
        createMenu("Fish Curry Vindaloo (spicy)",15.95,35,"n");
        createMenu("Shrimp Curry Vindaloo (spicy)",15.95,35,"n");
        createMenu("Chicken Korma with Nuts & Raisins",12.95,35,"n");
        createMenu("Chicken Vindaloo",12.95,35,"n");
        createMenu("Chicken Mango",12.95,35,"n");
        createMenu("Chicken Saag",12.95,35,"n");
        createMenu("Lamb Korma with Nuts & Raisins",14.95,35,"n");
        createMenu("Lamb Vindaloo",14.95,35,"n");
        createMenu("Shrimp Saag",15.95,35,"n");
        createMenu("Lamb Saag",14.95,35,"n");
        createMenu("Naan",2.25,36,"n");
        createMenu("Garlic Naan",2.75,36,"n");
        createMenu("Onion Naan",2.95,36,"n");
        createMenu("Lamb Naan",4.95,36,"n");
        createMenu("Chicken Naan",4.95,36,"n");
        createMenu("Cheese Naan",4.95,36,"n");
        createMenu("Aloo Paratha",4.95,36,"n");
        createMenu("Paratha",3.5,36,"n");
        createMenu("Tandoori Roti",2.25,36,"n");
        createMenu("Chapati",2.25,36,"n");
        createMenu("Basmati Rice",1.95,36,"n");
        createMenu("Basmati of the Day",3.95,36,"n");
        createMenu("Brown Basmati Rice",2.95,36,"n");
        createMenu("Aloo Naan",4.95,36,"n");
        createMenu("Nimbu Paani",2.5,37,"n");
        createMenu("Mango Lassi",4.25,37,"n");
        createMenu("Sweet Lassi",2.95,37,"n");
        createMenu("Masala Lassi",2.95,37,"n");
        createMenu("Indian Chai",2.95,37,"n");
        createMenu("Indian Iced Tea",2.95,37,"n");
        createMenu("Ginger Brew",3.95,37,"n");
        createMenu("COKE, DIET COKE, SPRITE",2.25,37,"n");
        createMenu("COFFEE",2.95,37,"n");
        createMenu("HOT TEAS",2.95,37,"n");
        createMenu("Scrambled Egg Tacos",8.5,38,"n");
        createMenu("Potato Tacos",8.5,38,"n");
        createMenu("Nutella Sandwich",8.5,38,"n");
        createMenu("Quesadilla con Huevos",12.5,38,"n");
        createMenu("Croque Monsieur",9.5,38,"n");
        createMenu("Croque Madame",10.5,38,"n");
        createMenu("Egg Sandwich",10.5,38,"n");
        createMenu("Breakfast Sundae",9.5,39,"n");
        createMenu("Lisa's Oatmeal",9.5,39,"n");
        createMenu("Grains and Cereals",3.75,39,"n");
        createMenu("Toast, with butter and jams",3.95,40,"n");
        createMenu("Cinnamon toast",3.95,40,"n");
        createMenu("Bagel, with butter and jams",3.95,40,"n");
        createMenu("Bagel, with cream cheese and jams",4.5,40,"n");
        createMenu("Zucchini bread",2.95,40,"n");
        createMenu("Zucchini bread, by the loaf",6.95,40,"n");
        createMenu("Quinoa and Eggs",12.5,41,"n");
        createMenu("Michael's Breakfast",10.95,41,"n");
        createMenu("Charlie's Breakfast",10.95,41,"n");
        createMenu("Emily's Breakfast",10.95,41,"n");
        createMenu("Vegetable Scramble",11.5,41,"n");
        createMenu("Original Joe's Special",12.5,41,"n");
        createMenu("Andouille Sausage Scramble",12.5,41,"n");
        createMenu("Lox and Eggs",12.5,41,"n");
        createMenu("Mushroom and Greens Scramble",11.5,41,"n");
        createMenu("BBQ Chicken and Andouille Sausage",11.5,43,"n");
        createMenu("Quinoa, Sweet Potato and Smoked Salmon Hash",12.5,43,"n");
        createMenu("Vegetable Hash",12.5,43,"n");
        createMenu("Avocado and Bacon",12.5,44,"n");
        createMenu("Mushroom",12.5,44,"n");
        createMenu("Cobb",12.5,44,"n");
        createMenu("Spinach",11.5,45,"n");
        createMenu("French Toast",9.95,45,"n");
        createMenu("Caramel-Pecan French Toast",11.5,45,"n");
        createMenu("Buttermilk Pancakes",6.5,45,"n");
        createMenu("Blueberry Multi Grain Pancakes",7.5,45,"n");
        createMenu("Corn Cakes",10.5,45,"n");
        createMenu("Eggs Benedict",11.5,42,"n");
        createMenu("Southwestern Benedict",12.5,42,"n");
        createMenu("Crab Cake Benedict",16.5,42,"n");
        createMenu("Spinach and Heirloom Tomato Benedict",11.5,42,"n");
        createMenu("One Egg",8.95,46,"n");
        createMenu("Pancakes and Eggs",10.95,46,"n");
        createMenu("Catherine's Breakfast",9.5,46,"n");
        createMenu("The Green Street Bloody Mary",10.5,47,"n");
        createMenu("The Green Street Mimosa",10,47,"n");
        createMenu("White Peach Bellini",11.5,47,"n");
        createMenu("The Green Street Stoli Screwdriver",10.5,47,"n");
        createMenu("The Breakfast Colada",10.5,47,"n");
        createMenu("The Bombay Gin Fizz",10.5,47,"n");
        createMenu("China Mist House Brewed Iced Tea",3.75,48,"n");
        createMenu("Jones Coffee, Regular and Decaf",3.75,48,"n");
        createMenu("Hot Leaves Teas",3.75,48,"n");
        createMenu("Coke, Diet Coke, Sprite, Dr. Pepper",3.75,48,"n");
        createMenu("Milk, Regular, Low and Non Fat",3.75,48,"n");
        createMenu("Republic of Tea Ginger Peach Decaf",6.95,48,"n");
        createMenu("I.B.C. Root Beer & Cream Soda",4.95,48,"n");
        createMenu("Fresh Strawberry Lemonade",4.5,48,"n");
        createMenu("Cranberry Juice",4.25,48,"n");
        createMenu("Fresh Fruit Juices, Large",5.5,48,"n");
        createMenu("Tomato Juice",3.95,48,"n");
        createMenu("Pellegrino Sparkling Water (Liter)",8.5,48,"n");
        createMenu("Chicken Liver Toast",3,49,"n");
        createMenu("Spicy Beef Tendon Chip",7,49,"n");
        createMenu("Marrow Bone",9,49,"n");
        createMenu("Lettuce",11,49,"n");
        createMenu("Pig Tails",11,49,"n");
        createMenu("Crispy Pig Head",12,49,"n");
        createMenu("Fried Brussels Sprouts",12,49,"n");
        createMenu("Beef Heart",12,49,"n");
        createMenu("Melted Petit Basque",12,49,"n");
        createMenu("Pig Ear",12,49,"n");
        createMenu("Tandoori Octopus",13,49,"n");
        createMenu("Barbeque Pork Belly Sandwiches",13,49,"n");
        createMenu("Shrimp & Rabbit Sausage Spring Roll",14,49,"n");
        createMenu("Veal Brains",14,49,"n");
        createMenu("Hamachi Tostada",15,49,"n");
        createMenu("Chicken Fried Sweetbreads",15,49,"n");
        createMenu("Potato Agnolotti",18,49,"n");
        createMenu("Poutine",18,49,"n");
        createMenu("Grilled Quail",19,49,"n");
        createMenu("Balsamic Pork Ribs",19,49,"n");
        createMenu("Duck Breast",21,49,"n");
        createMenu("Flat Iron",28,49,"n");
        createMenu("Braised Rabbit Legs",29,49,"n");
        createMenu("Tres Leches",8,49,"n");
        createMenu("Yogurt Panna Cotta",8,49,"n");
        createMenu("Yogurt Panna Cotta",8,49,"n");
        createMenu("Bacon Chocolate Crunch Bar",8,49,"n");
        createMenu("Huckleberry Pavlova",8,49,"n");
        createMenu("Olives baked",9,49,"n");
        createMenu("Eggplant Caponata",9,49,"n");
        createMenu("Fried Squash Blossoms",12,49,"n");
        createMenu("Fried cauliflower",9,49,"n");
        createMenu("Roasted carrots",9,49,"n");
        createMenu("Spicy Wax Beans",9,49,"n");
        createMenu("Fried Potatoes",9,49,"n");
        createMenu("Corn baked",11,49,"n");
        createMenu("Shishito Peppers baked",9,49,"n");
        createMenu("Arancine Bolognese",9,49,"n");
        createMenu("Marinated Baby Peppers with Tuna",11,50,"n");
        createMenu("Shrimp and Melon",12,50,"n");
        createMenu("Crispy Goat Cheese",11,50,"n");
        createMenu("Mussels baked",11,50,"n");
        createMenu("Chicken Wings devilled",11,50,"n");
        createMenu("Bone Marrow baked",12,50,"n");
        createMenu("Meatballs baked",12,50,"n");
        createMenu("Mixed Salad",8,51,"n");
        createMenu("Mozza Caprese",13,51,"n");
        createMenu("Nancy's Chopped Salad",17,51,"n");
        createMenu("Arugula, mushrooms & Piave",13,51,"n");
        createMenu("Red salad",14,51,"n");
        createMenu("Tricolor",13,51,"n");
        createMenu("Little Gem Lettuces, Dates, Red Onion & Gorgonzola",13,51,"n");
        createMenu("Speck",12,52,"n");
        createMenu("Calabrese Salami",11,52,"n");
        createMenu("Piedmont Salami",11,52,"n");
        createMenu("Prosciutto di Parma",12,52,"n");
        createMenu("Parma Ham & Mozzarella di Bufala",18,52,"n");
        createMenu("Mixed sliced",21,52,"n");
        createMenu("White bread",4,53,"n");
        createMenu("White Beans to Tuscany",9,53,"n");
        createMenu("Chicken Liver",9,53,"n");
        createMenu("Ricotta, Chestnut Honey, hazelnut toast",12,53,"n");
        createMenu("Fava Bean Puree",15,53,"n");
        createMenu("Inglese Pea Crouton",12,53,"n");
        createMenu("Braised Tuna Olive Oil, Egg, Capers & Anchovy",16,54,"n");
        createMenu("Mozzarella di Bufala, Parma Ham & Rocket",15,54,"n");
        createMenu("Mortadella, salami Finocchiona, Green Olive, Gardener & Provolone",16,54,"n");
        createMenu("Monday - Eggplant Parmigiana",17,55,"n");
        createMenu("Tuesday - Brisket baked",18,55,"n");
        createMenu("Wednesday - Chicken Milanese",20,55,"n");
        createMenu("Thursday - Baked Ribs",25,55,"n");
        createMenu("Friday - Soft Shell Crab",23,55,"n");
        createMenu("Saturday - Baked chicken",24,55,"n");
        createMenu("Sunday - Lasagne",21,55,"n");
        createMenu("Pizzetta",17,56,"n");
        createMenu("Squash Blossoms, Tomato & Burrata",15,56,"n");
        createMenu("Garlic and oil",23,56,"n");
        createMenu("Mixed mushrooms, Fontina, Taleggio & Thyme",11,56,"n");
        createMenu("Margherita",17,56,"n");
        createMenu("Long Cooked Broccoli, Caciocavallo & Chiles",15,56,"n");
        createMenu("Tomato, Sicilian Oregano & Extra Virgin Olive Oil",11,56,"n");
        createMenu("White",18,56,"n");
        createMenu("White Anchovy, Tomato & Fresno Chiles",16,56,"n");
        createMenu("Rapini, Cherry Tomatoes, Anchovies, Olives, Chiles & Parmesan",16,56,"n");
        createMenu("Fennel Sausage, cream, Mozzarella, Red Onions & Scallions",17,56,"n");
        createMenu("Goat Cheese, Leeks, Scallions, Garlic & Bacon",17,56,"n");
        createMenu("Bacon, Salami, Fennel Sausage, Pillow, Tomato & Mozzarella",18,56,"n");
        createMenu("Pizza alla Benno",17,56,"n");
        createMenu("Buffalo Mozzarella, Tomato, Basil & Extra Virgin Olive Oil",20,57,"n");
        createMenu("Tomato, Sicilian Oregano & Extra Virgin Olive Oil",17,57,"n");
        createMenu("Prosciutto, Arugula, Tomato & Mozzarella di Bufala",23,57,"n");
        createMenu("Napolitana",23,57,"n");
        createMenu("Apricot bowl",10,58,"n");
        createMenu("Strawberry Ice Cream Pie",10,58,"n");
        createMenu("Caramel bowl",10,58,"n");
        createMenu("Butterscotch Pudding",10,58,"n");

    }

    private long createMenu(String s, double v ,double i, String type) {
        SQLiteDatabase db=this.getWritableDatabase();
        ContentValues initialValues = new ContentValues();
        initialValues.put(COLUMN_MENU, s);
        initialValues.put(COLUMN_PRICE, v);
        initialValues.put(COLUMN_VNEG, type);
        initialValues.put(COLUMN_CATEGORYID, i);
        return db.insert("fooditems", null, initialValues);
    }

    public void dropTable()
    {
        SQLiteDatabase db=getWritableDatabase();
        db.execSQL("DROP TABLE IF EXISTS " + TABLE1);
        db.execSQL("DROP TABLE IF EXISTS " + TABLE2);
        db.execSQL("DROP TABLE IF EXISTS " + TABLE3);
        onCreate(db);
    }
}